version: '3.6'
services:
  mysqldb:
    image: mysql:8.0.0
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - znet
    environment:
      MYSQL_ROOT_PASSWORD: dbuserpassword
  redis-server:
    image: redis:4.0
    restart: always
    command: /bin/bash -c 'redis-server --appendonly yes'
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - znet
  api:
    image: zblog.api
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:80"
    restart: always
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: 
      - mysqldb
      - redis-server
    networks:
      - znet

volumes:
  mysql-data:
    driver: local
  redis:
    driver: local

networks:
  znet:
    driver: bridge