version: '3.4'

services:
  mysqldb:
    image: mysql:8.0.0
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
  redis-server:
    image: redis:latest
    volumes:
      - redis:/data
  zblog.api:
    image: ${DOCKER_REGISTRY-}zblogapi
    build:
      context: .
      dockerfile: src/app/ZBlog.Api/Dockerfile

volumes:
  mysql-data:
    driver: local
  redis:
    driver: local